import { createHmac, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";
import { isSessionRevoked } from "@/lib/sessionRegistry";

/**
 * Self-contained admin session handling.
 *
 * A session is a signed token: `base64url(payload).base64url(hmac)`.
 * The HMAC is keyed with AUTH_SECRET, so a token cannot be forged client-side.
 * Verification is pure crypto plus an in-memory revocation lookup, which keeps
 * it usable from proxy.ts.
 */

/**
 * The `__Host-` prefix is enforced by the browser: the cookie is refused unless
 * it is Secure, Path=/, and carries no Domain. That blocks a subdomain — or
 * anything that manages to run on one — from planting a session cookie for the
 * apex. The prefix requires HTTPS, so plain-http local development keeps the
 * bare name.
 */
export const SESSION_COOKIE =
  process.env.NODE_ENV === "production" ? "__Host-divanex_session" : "divanex_session";

/** 8 hours. Short enough that a leaked cookie expires on its own. */
const SESSION_TTL_SECONDS = 8 * 60 * 60;

const SCRYPT_KEYLEN = 64;

export interface SessionPayload {
  sub: string;
  exp: number;
  /** Token id, so a single session can be revoked at logout. */
  jti?: string;
  /** Issued-at, so every session for a subject can be revoked at once. */
  iat?: number;
}

/**
 * Cookie attributes for the admin session.
 *
 * SameSite=Strict rather than Lax: the console is reached by direct navigation
 * or a bookmark, so the cost is that a cross-site link lands on the login
 * screen once, and the benefit is that no cross-site navigation carries admin
 * credentials at all.
 */
export function adminCookieOptions(maxAge: number) {
  return {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "strict" as const,
    path: "/",
    maxAge,
  };
}

function getAuthSecret(): string {
  const secret = process.env.AUTH_SECRET;
  if (!secret || secret.length < 32) {
    throw new Error(
      "AUTH_SECRET is missing or too short (needs >= 32 chars). Run `node scripts/generate-admin-credentials.js`."
    );
  }
  return secret;
}

function b64url(input: Buffer | string): string {
  return Buffer.from(input).toString("base64url");
}

function sign(data: string, secret: string): string {
  return createHmac("sha256", secret).update(data).digest("base64url");
}

/** Constant-time string compare that never throws on length mismatch. */
function safeEqual(a: string, b: string): boolean {
  const bufA = Buffer.from(a);
  const bufB = Buffer.from(b);
  if (bufA.length !== bufB.length) {
    // Still burn a comparison so the timing profile stays flat.
    timingSafeEqual(bufA, bufA);
    return false;
  }
  return timingSafeEqual(bufA, bufB);
}

export function createSessionToken(subject: string): { token: string; maxAge: number } {
  const secret = getAuthSecret();
  const now = Math.floor(Date.now() / 1000);
  const payload: SessionPayload = {
    sub: subject,
    exp: now + SESSION_TTL_SECONDS,
    iat: now,
    jti: randomBytes(16).toString("base64url"),
  };
  const encoded = b64url(JSON.stringify(payload));
  return { token: `${encoded}.${sign(encoded, secret)}`, maxAge: SESSION_TTL_SECONDS };
}

/** Returns the session payload, or null if the token is absent, forged, or expired. */
export function verifySessionToken(token: string | undefined | null): SessionPayload | null {
  if (!token) return null;

  const dot = token.lastIndexOf(".");
  if (dot <= 0) return null;

  const encoded = token.slice(0, dot);
  const signature = token.slice(dot + 1);

  let secret: string;
  try {
    secret = getAuthSecret();
  } catch {
    // No secret configured: fail closed rather than letting everyone in.
    return null;
  }

  if (!safeEqual(signature, sign(encoded, secret))) return null;

  try {
    const payload = JSON.parse(Buffer.from(encoded, "base64url").toString()) as SessionPayload;
    if (typeof payload.exp !== "number" || payload.exp < Math.floor(Date.now() / 1000)) {
      return null;
    }
    // A signed, unexpired token is still refused once its session has been
    // logged out or the account has had every session revoked.
    if (isSessionRevoked(payload)) return null;
    return payload;
  } catch {
    return null;
  }
}

/** Hash format: `scrypt$<saltHex>$<hashHex>` — generated by scripts/generate-admin-credentials.js. */
export function hashPassword(password: string, salt = randomBytes(16).toString("hex")): string {
  const derived = scryptSync(password, salt, SCRYPT_KEYLEN).toString("hex");
  return `scrypt$${salt}$${derived}`;
}

export function verifyPassword(password: string, stored: string | undefined): boolean {
  if (!stored) return false;
  const parts = stored.split("$");
  if (parts.length !== 3 || parts[0] !== "scrypt") return false;

  const [, salt, expected] = parts;
  try {
    const derived = scryptSync(password, salt, SCRYPT_KEYLEN).toString("hex");
    return safeEqual(derived, expected);
  } catch {
    return false;
  }
}

/** Constant-time comparison for short secrets (OTP codes, tokens). */
export function timingSafeCompare(a: string, b: string): boolean {
  return safeEqual(a, b);
}

/** Keyed digest of a short-lived secret, so it is never held in plaintext. */
export function hashShortSecret(value: string): string {
  return createHmac("sha256", getAuthSecret()).update(value).digest("base64url");
}
